package com.example.banking.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;

@Schema(description = "Data Transfer Object for Account")
public class AccountDTO {
    @Schema(description = "Unique identifier of the account, auto-generated by the server", example = "1", accessMode = Schema.AccessMode.READ_ONLY)
    private Long id;

    @Schema(description = "Balance of the account (up to two decimal places)", example = "1000.00")
    private BigDecimal balance;

    @Schema(description = "First name of the account holder", example = "John", required = true)
    private String firstName;

    @Schema(description = "Last name of the account holder", example = "Doe", required = true)
    private String lastName;

    public AccountDTO() {}

    public AccountDTO(Long id, BigDecimal balance, String firstName, String lastName) {
        this.id = id;
        this.balance = balance;
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public BigDecimal getBalance() { return balance; }
    public void setBalance(BigDecimal balance) { this.balance = balance; }
    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }
    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }
}